package com.corba.generatedfilesidl;


/**
* Comminication/HandlerMessage.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CommicationIDL.idl
* Quarta-feira, 1 de Maio de 2013 11h03min57s GMT-03:00
*/

public interface HandlerMessage extends HandlerMessageOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HandlerMessage
