package com.client.corbajms.generatedfilesidl;

/**
 * Comminication/HandlerMessage.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from CommicationIDL.idl Segunda-feira, 6 de Maio de
 * 2013 15h35min24s GMT-03:00
 */

public interface HandlerMessage extends HandlerMessageOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
} // interface HandlerMessage