package com.client.corbajms.generatedfilesidl;

/**
 * Comminication/HandlerMessagePOA.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from CommicationIDL.idl Terça-feira, 7 de Maio de
 * 2013 15h54min44s GMT-03:00
 */

@SuppressWarnings("unchecked")
public abstract class HandlerMessagePOA extends org.omg.PortableServer.Servant
		implements HandlerMessageOperations,
		org.omg.CORBA.portable.InvokeHandler {

	// Constructors

	@SuppressWarnings("rawtypes")
	private static java.util.Hashtable _methods = new java.util.Hashtable();
	static {
		_methods.put("registerUser", new java.lang.Integer(0));
		_methods.put("sendMessage", new java.lang.Integer(1));
		_methods.put("retrieveQueueAndTopics", new java.lang.Integer(2));
		_methods.put("retrieveMessages", new java.lang.Integer(3));
	}

	public org.omg.CORBA.portable.OutputStream _invoke(String $method,
			org.omg.CORBA.portable.InputStream in,
			org.omg.CORBA.portable.ResponseHandler $rh) {
		org.omg.CORBA.portable.OutputStream out = null;
		java.lang.Integer __method = (java.lang.Integer) _methods.get($method);
		if (__method == null)
			throw new org.omg.CORBA.BAD_OPERATION(0,
					org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

		switch (__method.intValue()) {
		case 0: // Comminication/HandlerMessage/registerUser
		{
			String username = in.read_string();
			this.registerUser(username);
			out = $rh.createReply();
			break;
		}

		case 1: // Comminication/HandlerMessage/sendMessage
		{
			Message message = MessageHelper.read(in);
			this.sendMessage(message);
			out = $rh.createReply();
			break;
		}

		case 2: // Comminication/HandlerMessage/retrieveQueueAndTopics
		{
			String $result[] = null;
			$result = this.retrieveQueueAndTopics();
			out = $rh.createReply();
			CollectionStringHelper.write(out, $result);
			break;
		}

		case 3: // Comminication/HandlerMessage/retrieveMessages
		{
			String origin = in.read_string();
			String $result[] = null;
			$result = this.retrieveMessages(origin);
			out = $rh.createReply();
			CollectionStringHelper.write(out, $result);
			break;
		}

		default:
			throw new org.omg.CORBA.BAD_OPERATION(0,
					org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
		}

		return out;
	} // _invoke

	// Type-specific CORBA::Object operations
	private static String[] __ids = { "IDL:Comminication/HandlerMessage:1.0" };

	public String[] _all_interfaces(org.omg.PortableServer.POA poa,
			byte[] objectId) {
		return (String[]) __ids.clone();
	}

	public HandlerMessage _this() {
		return HandlerMessageHelper.narrow(super._this_object());
	}

	public HandlerMessage _this(org.omg.CORBA.ORB orb) {
		return HandlerMessageHelper.narrow(super._this_object(orb));
	}

} // class HandlerMessagePOA
