package com.corba.generatedfilesidl;

/**
 * Comminication/Message.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from CommicationIDL.idl Quarta-feira, 1 de Maio de
 * 2013 11h03min57s GMT-03:00
 */

public final class Message implements org.omg.CORBA.portable.IDLEntity {
	
	private static final long serialVersionUID = 1L;
	
	public String emissor = null;
	public String corpo = null;

	public Message() {
	} // ctor

	public Message(String _emissor, String _corpo) {
		emissor = _emissor;
		corpo = _corpo;
	} // ctor

} // class Message
