package com.server.corbajms.generatedfilesidl;

/**
 * Comminication/CollectionStringHolder.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from CommicationIDL.idl Terça-feira, 7 de
 * Maio de 2013 15h54min44s GMT-03:00
 */

public final class CollectionStringHolder implements
		org.omg.CORBA.portable.Streamable {
	public String value[] = null;

	public CollectionStringHolder() {
	}

	public CollectionStringHolder(String[] initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = CollectionStringHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		CollectionStringHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return CollectionStringHelper.type();
	}

}
