package com.server.corbajms.generatedfilesidl;

/**
 * Comminication/HandlerMessageOperations.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from CommicationIDL.idl Quarta-feira, 1 de
 * Maio de 2013 11h03min57s GMT-03:00
 */

public interface HandlerMessageOperations {
	String send_msg(Message email);
} // interface HandlerMessageOperations
