package com.server.corbajms.generatedfilesidl;

/**
 * Comminication/HandlerMessageOperations.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from CommicationIDL.idl Segunda-feira, 6
 * de Maio de 2013 16h58min39s GMT-03:00
 */

public interface HandlerMessageOperations {
	void sendMessage(Message message);

	String[] retrieveQueueAndTopics();

	String[] retrieveMessages();
} // interface HandlerMessageOperations
