package com.server.corbajms.generatedfilesidl;

/**
 * Comminication/MessageHelper.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from CommicationIDL.idl Segunda-feira, 6 de Maio de
 * 2013 16h58min39s GMT-03:00
 */

abstract public class MessageHelper {
	private static String _id = "IDL:Comminication/Message:1.0";

	public static void insert(org.omg.CORBA.Any a, Message that) {
		org.omg.CORBA.portable.OutputStream out = a.create_output_stream();
		a.type(type());
		write(out, that);
		a.read_value(out.create_input_stream(), type());
	}

	public static Message extract(org.omg.CORBA.Any a) {
		return read(a.create_input_stream());
	}

	private static org.omg.CORBA.TypeCode __typeCode = null;
	private static boolean __active = false;

	synchronized public static org.omg.CORBA.TypeCode type() {
		if (__typeCode == null) {
			synchronized (org.omg.CORBA.TypeCode.class) {
				if (__typeCode == null) {
					if (__active) {
						return org.omg.CORBA.ORB.init()
								.create_recursive_tc(_id);
					}
					__active = true;
					org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember[3];
					org.omg.CORBA.TypeCode _tcOf_members0 = null;
					_tcOf_members0 = org.omg.CORBA.ORB.init().create_string_tc(
							0);
					_members0[0] = new org.omg.CORBA.StructMember("issuing",
							_tcOf_members0, null);
					_tcOf_members0 = org.omg.CORBA.ORB.init().create_string_tc(
							0);
					_members0[1] = new org.omg.CORBA.StructMember(
							"destination", _tcOf_members0, null);
					_tcOf_members0 = org.omg.CORBA.ORB.init().create_string_tc(
							0);
					_members0[2] = new org.omg.CORBA.StructMember("body",
							_tcOf_members0, null);
					__typeCode = org.omg.CORBA.ORB.init().create_struct_tc(
							MessageHelper.id(), "Message", _members0);
					__active = false;
				}
			}
		}
		return __typeCode;
	}

	public static String id() {
		return _id;
	}

	public static Message read(org.omg.CORBA.portable.InputStream istream) {
		Message value = new Message();
		value.issuing = istream.read_string();
		value.destination = istream.read_string();
		value.body = istream.read_string();
		return value;
	}

	public static void write(org.omg.CORBA.portable.OutputStream ostream,
			Message value) {
		ostream.write_string(value.issuing);
		ostream.write_string(value.destination);
		ostream.write_string(value.body);
	}

}
