module Comminication{
	struct Message{
		string issuing;
		string destination;
		string body;
	};
	interface HandlerMessage{
		void sendMessage(in Message message);
		string retrieveQueueAndTopics();
	};
};