module Comminication{
	typedef sequence <string> CollectionString;

	struct Message{
		string issuing;
		string destination;
		string body;
	};
	
	interface HandlerMessage{
		void registerUser(in string username);
		void sendMessage(in Message message);
		CollectionString retrieveQueueAndTopics();
		CollectionString retrieveMessages(in string origin);
	};
};